### ISSUE TITLE
How to download the 4mm neuroquery model?

### ISSUE THREAD

**Issue by A-Telfer** [neuroquery/neuroquery#24]
Hi! I wanted to try recreating the neuroquery.org images in a python notebook, but noticed there's a resolution difference

My first thought was just to write a webscraper/selenium script to generate them but then I saw your note
> Please do not scrape this website
> We run this website as a demo of the capabilities of the NeuroQuery model and as a service to the neuroscience community. Please do not run an automated tool to scrape results from this website. Instead, we provide the Python library (for both training and inference) [here](https://github.com/neuroquery/neuroquery). The library also enables downloading the trained model that runs on the website.

However, using the minimal_example.ipynb notebook returned very low resolution images. 

So I took a look at the training_neuroquery.ipynb and saw this
```
# You can set target_affine to a different value to increase image resolution
# or reduce computation time. The model on neuroquery.org uses 4 mm
# resolution i.e. target_affine=(4, 4, 4)
```
- I take it that the default model used in python used a different resolution? 

Training the model myself is taking very long. If it's just a matter of uploading a folder, would it be possible to post the full neuroquery.org model online?

---
p.s. the ensemble model in datasets.py doesn't work with the minimal_example.ipynb code

e.g. this breaks 
```
from neuroquery import fetch_neuroquery_model
neuroquery_data = fetch_neuroquery_model(model_name="ensemble_model_2020-02-12")
```
- it seems to have worked after I manually copied over some folders from the other model, so I think the regression and smoothing folders are just missing

**Comment by A-Telfer** [comment]
I looked through the neuroquery.org network downloads and saw this
![image](https://user-images.githubusercontent.com/75952206/204395935-ecb8bb20-533c-44d1-8ada-41d307ebfa5f.png)

Was it 2mm all along??

**Comment by A-Telfer** [comment]
I was able to use the existing model to get results that appeared closer to the online model using the default python one and resampling it to 1x1x1mm

**Comment by jeromedockes** [comment]
Hello, sorry for the late reply! I was travelling last week.

You can download all the images shown on neuroquery.org from here:

  https://osf.io/j9za6

More generally this OSF project:

  https://osf.io/5qjpb/

Has the maps for all articles and terms, brain mask used, and some other resources.

The minimal_example.py produces images of resolution 4x4x4mm, which is what was used for the experiments in the paper and is indeed a low resolution. But that is indeed the resolution of the model used in the paper and the website. 

The model downloaded automatically and used by the minimal_example is the same one that is used on the neuroquery.org website.
The images you can obtain by clicking the "Download" button on neuroquery.org have the same 4x4x4mm resolution.

The 2mm you see is just the default resolution of the anatomical template used for the background (in the regions where the image is thresholded).
The images are resampled to that template for display which is why they appear to have a higher resolution in the display.

Resampling to the resolution you need, as you did, is the right way to go IMO. thanks for sharing your solution!
